services:
  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - /home/hass/mosquitto/config:/mosquitto/config:ro
      - /home/hass/mosquitto/log:/mosquitto/log
      - data:/mosquitto/data/
    ports:
      - 1883:1883
      - 9001:9001

volumes:
  mosquitto_data: