version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect. See https://github.com/qdm12/gluetun/wiki/Connect-a-container-to-gluetun#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 6789:6789 # nzbget
    volumes:
      - /home/arbiter/media-management/glutun:/gluetun
      - /home/arbiter/media-management/glutun/custom.conf:/gluetun/custom.conf:ro
    environment:
      # See https://github.com/qdm12/gluetun/wiki
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      # - SERVER_COUNTRIES=Germany
      # OpenVPN:
      #- OPENVPN_CUSTOM_CONFIG=/gluetun/custom.conf
      #- OPENVPN_USER=$OPENVPN_USER
      #- OPENVPN_PASSWORD=$OPENVPN_PASSWORD
      #- OPENVPN_CIPHER=aes-128-cbc
      #- OPENVPN_ROOT=yes
      #- OPENVPN_VERBOSITY=6
      # Wireguard:
      - VPN_ENDPOINT_IP=93.177.73.114
      - VPN_ENDPOINT_PORT=1443
      - WIREGUARD_PUBLIC_KEY=$WIREGUARD_PUBLIC_KEY
      - WIREGUARD_PRIVATE_KEY=$WIREGUARD_PRIVATE_KEY
      - WIREGUARD_ADDRESSES=10.13.79.145/24
      # Timezone for accurate log times
      - TZ=Europe/Berlin
      # For debugging remove after
      - FIREWALL=on
      - DOT=on
      - FIREWALL_DEBUG=off
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - NZBGET_USER=nzbget #optional
      - NZBGET_PASS=tegbzn6789 #optional
    volumes:
      - /home/arbiter/media-management/nzbget/config:/config
      - /home/arbiter/media-management/nzbget/downloads:/downloads #optional
    restart: unless-stopped
    network_mode: "service:gluetun"
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=username #optional
      - PASS=password #optional
      #- WHITELIST=iplist #optional
      #- PEERPORT=peerport #optional
      #- HOST_WHITELIST=dnsname list #optional
    volumes:
      - /home/arbiter/media-management/transmission/config:/config
      - /home/arbiter/media-management/transmission/downloads:/downloads
      - /home/arbiter/media-management/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /home/arbiter/media-management/sonarr/data:/config
      - /home/arbiter/media-management/sonarr/tv:/tv #optional
      - /home/arbiter/media-management/sonarr/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /home/arbiter/media-management/radarr/data:/config
      - /home/arbiter/media-management/radarr/movies:/movies #optional
      - /home/arbiter/media-management/radarr/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
