version: "3"
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=Europe/London
    volumes:
      - /home/hass/config:/config
    ports:
      - 8123:8123 #optional
    restart: unless-stopped