version: '3'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - ./influxdb:/var/lib/influxdb
    restart:
      always
  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "1000:0"
    ports:
      - 3001:3000
    volumes:
      - ./grafana:/var/lib/grafana
    restart:
      always