version: "3"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - ./plex/config:/config
      - ./plex/tv:/tv
      #- $PLEX_ROOT_A/tv-shows:/tv_a
      #- $PLEX_ROOT_B/tv-shows:/tv_b
      - ./plex/movies:/movies
      - ./plex/anime:/anime
      - ./plex/music:/music
    devices:
      - "/dev/dri:/dev/dri"
    restart: unless-stopped